services:
  frontend:
    image: node:18-alpine
    container_name: tami-front
    working_dir: /app
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --host --port 3002"
    environment:
      - NODE_ENV=development


volumes:
  node_modules:

